# .github/workflows/update-table.yml
name: Update Table Row Numbers

on:
  push:
    paths:
      - 'README.md'

jobs:
  update-table:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the version of Node.js to use

      - name: Install dependencies
        run: npm install

      - name: Update row numbers in README.md
        run: node updateTable.js

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Automatically updated row numbers in README.md"
          git push
